apiVersion: batch/v1
kind: Job
metadata:
  name: vllm-benchmark
  namespace: vllm
spec:
  parallelism: 4
  completions: 4
  template:
    metadata:
      labels:
        app: vllm-benchmark
    spec:
      serviceAccountName: deepseek-r1
      restartPolicy: Never
      containers:
        - name: benchmark
          image: quay.io/tms/llm-d-cuda-dev:v0.5.0-arm64
          env:
            - name: VLLM_HTTP_TIMEOUT_KEEP_ALIVE
              value: "1000"
          command:
            - /bin/bash
            - -c
          args:
            - |-
              source /opt/vllm/bin/activate
              # Wait for vLLM server to be ready
              echo "Waiting for vLLM prefill server to be ready..."
              until curl -f http://llm-d-inference-gateway-istio.vllm.svc.cluster.local/health > /dev/null 2>&1; do
                echo "Prefill server not ready, waiting..."
                sleep 10
              done

              echo "vLLM prefill server is ready!"

              echo "Running small bench first"

              vllm bench serve \
                --base-url http://llm-d-inference-gateway-istio.vllm.svc.cluster.local \
                --model nvidia/DeepSeek-R1-0528-FP4-v2 \
                --dataset-name random \
                --random-input-len 500 \
                --random-output-len 1500 \
                --seed $(date +%M%H%M%S) \
                --num-prompts 4096 \
                --max-concurrency 1024 \
                --request-rate 1024 \
                --ignore-eos



              echo "Starting vLLM benchmark with DeepSeek-V3.1."
              vllm bench serve \
                --base-url http://llm-d-inference-gateway-istio.vllm.svc.cluster.local \
                --model nvidia/DeepSeek-R1-0528-FP4-v2 \
                --dataset-name random \
                --random-input-len 500 \
                --random-output-len 1500 \
                --seed 0 \
                --num-prompts 65536 \
                --seed $(date +%M%H%M%S) \
                --max-concurrency 1024 \
                --request-rate 1024 \
                --ignore-eos

              vllm bench serve \
                --base-url http://llm-d-inference-gateway-istio.vllm.svc.cluster.local \
                --model nvidia/DeepSeek-R1-0528-FP4-v2 \
                --dataset-name random \
                --random-input-len 2000 \
                --random-output-len 100 \
                --seed $(date +%M%H%M%S) \
                --num-prompts 65536 \
                --seed $(date +%M%H%M%S) \
                --max-concurrency 1024 \
                --request-rate 4096 \
                --ignore-eos

              vllm bench serve \
                --base-url http://llm-d-inference-gateway-istio.vllm.svc.cluster.local \
                --model nvidia/DeepSeek-R1-0528-FP4-v2 \
                --dataset-name random \
                --random-input-len 1000 \
                --random-output-len 1000 \
                --seed $(date +%M%H%M%S) \
                --num-prompts 65536 \
                --max-concurrency 1024 \
                --request-rate 4096 \
                --ignore-eos
          resources:
            requests:
              memory: "64Gi"
              cpu: "2"
            limits:
              memory: "64Gi"
              cpu: "4"
  backoffLimit: 3
