apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  - target:
      kind: LeaderWorkerSet
    patch: |-
      - op: replace
        path: /spec/leaderWorkerTemplate/workerTemplate/spec/volumes/1
        value:
          name: hf-cache
          hostPath:
            path: /mnt/local/hf-cache
            type: DirectoryOrCreate
      - op: replace
        path: /spec/leaderWorkerTemplate/workerTemplate/spec/volumes/2
        value:
          name: jit-cache
          hostPath:
            path: /mnt/local/jit-cache
            type: DirectoryOrCreate
